# Generated by Django 3.2.4 on 2021-07-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0003_userprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='descriptions',
            field=models.TextField(blank=True),
        ),
    ]
